[theme]
primaryColor = "#007bff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
# Permite subir archivos de LimeSurvey de hasta 200MB
maxUploadSize = 200

[browser]
# Hace que la interfaz se vea m√°s limpia en Android
toolbarMode = "minimal"
