[theme]
primaryColor = "#2E7D32"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F8E9"
textColor = "#212121"
font = "sans serif"
[server]
# Permite subir archivos de LimeSurvey de hasta 200MB
maxUploadSize = 200

[browser]
# Hace que la interfaz se vea m√°s limpia en Android
toolbarMode = "minimal"
